### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alejandrobustos** [booleancl/generator-blng#1]
This is the roadmap to the first version of the generator

As first priority...

- [ ] Fully integrated unit testing suite
- [ ] Subgenerators for:
  - [ ] Controllers
  - [ ] Services and Factories

Less priority features
- [ ] Create a Docker compatible image for this generator
- [ ] Create a docker image ready-to-use available from docker hub
